---
ansible_user: vxadmin
ansible_become: true
ansible_ssh_port: 55682
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# Public key path for distribution
pubkey_path: github_wsl_ansible_skidbladnir.pub

# MicroK8s install settings
microk8s_channel: "1.32/stable"
microk8s_classic: true
