- name: Ensure password authentication is disabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication\s+'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart SSH

- name: Ensure public key authentication is enabled
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication\s+'
    line: 'PubkeyAuthentication yes'
    state: present
  notify: Restart SSH

- name: Ensure sshd_config permissions
  file:
    path: /etc/ssh/sshd_config
    mode: '0644'
