---
# tasks file for enabling HA in MicroK8s
- name: Check number of control plane nodes online
  delegate_to: localhost
  run_once: true
  shell: >
    ansible -i inventory.yaml control_planes
    --one-line --list-hosts | tail -n +2 | wc -l
  register: cp_node_count

- name: Set fact for HA eligibility
  set_fact:
    enable_ha: "{{ cp_node_count.stdout | int >= 3 }}"
  when: cp_node_count is defined

- name: Enable HA on this node if eligible
  command: microk8s enable ha-cluster
  when: enable_ha | default(false)

- name: Confirm HA status
  command: microk8s status --wait-ready
  when: enable_ha | default(false)

- name: Skip HA on insufficient control nodes
  debug:
    msg: "HA not enabled: Fewer than 3 control plane nodes online."
  when: not enable_ha | default(false)
