---
# Entrypoint for all k8s-node tasks

- name: Include MicroK8s installation
  ansible.builtin.import_tasks: microk8s.yml

- name: Configure SSH if enabled
  ansible.builtin.import_tasks: ssh.yml
  when: configure_ssh

- name: Configure swap state
  ansible.builtin.import_tasks: swap.yml
  when: not swap_enabled

# Cluster health checks
- name: Include cluster HA setup
  ansible.builtin.import_tasks: ha-cluster.yml

- name: Include UFW configuration
  ansible.builtin.import_tasks: ufw.yml
