---
# Handles installing and preparing MicroK8s

- name: Ensure MicroK8s is absent (clean slate)
  ansible.builtin.shell: |
    sudo microk8s leave || true
    sudo microk8s reset --destroy-storage || true
    sudo snap remove microk8s || true
  ignore_errors: true

- name: Install MicroK8s
  community.general.snap:
    name: "{{ microk8s_snap_name }}"
    classic: "{{ microk8s_classic }}"
    channel: "{{ microk8s_channel }}"

- name: Wait for MicroK8s to be ready
  ansible.builtin.command: microk8s status --wait-ready

- name: Disable hostpath-storage if needed
  ansible.builtin.command: microk8s disable hostpath-storage
  when: disable_hostpath_storage
  ignore_errors: true
