- name: Harden SSH
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
  loop: "{{ ssh_hardening_rules }}"
  notify: Restart ssh
