---
# Placeholder UFW rules (deferred until post-bootstrap)

- name: Ensure UFW is installed
  ansible.builtin.package:
    name: ufw
    state: present

- name: Disable UFW before configuration
  ansible.builtin.command: ufw disable
  become: true
  ignore_errors: true

- name: Allow internal node communication (placeholder)
  ansible.builtin.command: ufw allow from 10.10.50.0/24
  become: true
  ignore_errors: true

- name: Enable UFW after configuration (optional)
  ansible.builtin.command: ufw enable
  become: true
  ignore_errors: true
  when: enable_ufw | default(false)
