---
- name: Distribute Ansible SSH Public Key to All Nodes
  hosts: all
  become: true
  gather_facts: false  # We don’t need facts for a simple file operation

  vars:
    pubkey_path: "{{ lookup('env','HOME') }}/github_wsl_ansible_skidbladnir.pub"
    ssh_user: vxadmin
    ssh_dir: "/home/{{ ssh_user }}/.ssh"
    authorized_keys_path: "{{ ssh_dir }}/authorized_keys"

  tasks:
    # Ensure the .ssh directory exists and is secured
    - name: Ensure .ssh directory exists for {{ ssh_user }}
      file:
        path: "{{ ssh_dir }}"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0700'

    # Check if authorized_keys file exists
    - name: Check for existing authorized_keys file
      stat:
        path: "{{ authorized_keys_path }}"
      register: authorized_keys_check

    # Optional backup for recovery
    - name: Backup existing authorized_keys if it exists
      copy:
        src: "{{ authorized_keys_path }}"
        dest: "{{ authorized_keys_path }}.bak"
        remote_src: yes
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: '0600'
      when: authorized_keys_check.stat.exists

    # Push Ansible's public key if not already present
    - name: Add Ansible public key to authorized_keys
      authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ lookup('file', pubkey_path) }}"
