- name: Join control plane - Thor
  hosts: k8s-thor
  serial: 1
  tasks:
    - name: Check if Thor is already part of the cluster
      delegate_to: k8s-odin
      command: microk8s kubectl get nodes -o name
      register: nodes_out

    - name: Set fact: should Thor join?
      set_fact:
        should_join: "{{ (nodes_out.stdout | default('')) is not search(inventory_hostname) }}"

    - name: Get join token from Odin
      delegate_to: k8s-odin
      command: microk8s add-node --control-plane
      register: join_info
      when: should_join

    - name: Extract join command
      set_fact:
        join_command: "{{ (join_info.stdout_lines | select('search', 'microk8s join') | list)[0] }}"
      when: should_join

    - name: Run join command on Thor
      command: "{{ join_command }}"
      register: join_command_result
      retries: 5
      delay: 10
      until: join_command_result.rc == 0
      when: should_join

    - name: Wait for Thor to be ready
      command: microk8s status --wait-ready
      when: should_join

    - name: Thor already in cluster
      debug:
        msg: "Thor is already part of the cluster, skipping join."
      when: not should_join

---

- name: Join control plane - Sindri
  hosts: k8s-sindri
  serial: 1
  tasks:
    - name: Check if Sindri is already part of the cluster
      delegate_to: k8s-odin
      command: microk8s kubectl get nodes -o name
      register: nodes_out

    - name: Set fact: should Sindri join?
      set_fact:
        should_join: "{{ (nodes_out.stdout | default('')) is not search(inventory_hostname) }}"

    - name: Get join token from Odin
      delegate_to: k8s-odin
      command: microk8s add-node --control-plane
      register: join_info
      when: should_join

    - name: Extract join command
      set_fact:
        join_command: "{{ (join_info.stdout_lines | select('search', 'microk8s join') | list)[0] }}"
      when: should_join

    - name: Run join command on Sindri
      command: "{{ join_command }}"
      register: join_command_result
      retries: 5
      delay: 10
      until: join_command_result.rc == 0
      when: should_join

    - name: Wait for Sindri to be ready
      command: microk8s status --wait-ready
      when: should_join

    - name: Sindri already in cluster
      debug:
        msg: "Sindri is already part of the cluster, skipping join."
      when: not should_join
