- name: Join worker nodes
  hosts: workers
  serial: 1
  tasks:
    - name: Get join token from Odin
      delegate_to: k8s-odin
      command: microk8s add-node
      register: join_info

    - name: Extract join command
      set_fact:
        join_command: "{{ join_info.stdout_lines | select('search', 'microk8s join') | list | first }}"

    - name: Run join command on worker
      command: "{{ join_command }}"
      retries: 5
      delay: 10
      until: join_command_result.rc == 0
      register: join_command_result

    - name: Wait for node to be ready
      command: microk8s status --wait-ready
