---
- name: Join worker nodes
  hosts: workers
  become: true
  serial: 1
  gather_facts: false

  tasks:
    - name: Generate join command from Odin
      delegate_to: k8s-odin
      command: microk8s add-node --token-ttl {{ microk8s_token_ttl | default(3600) }}
      register: join_info
      run_once: true

    - name: Extract join command
      set_fact:
        join_command: "{{ join_info.stdout_lines | select('search', '^microk8s join') | list | first }}"

    - name: Append --worker to join command
      set_fact:
        join_command: "{{ join_command }} --worker"

    - name: Run join command on worker
      command: "{{ join_command }}"
      register: join_command_result
      retries: 5
      delay: 10
      until: join_command_result.rc == 0

    - name: Wait for node to be ready
      command: microk8s status --wait-ready
