---
- name: Simple Node Health Check
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: Check uptime
      command: uptime
      register: uptime_out

    - name: Show uptime
      debug:
        var: uptime_out.stdout

    - name: List installed packages
      command: dpkg -l
      register: apt_list

    - name: Show first 10 packages
      debug:
        msg: "{{ apt_list.stdout_lines[:10] }}"
